sudo: required

language: java
jdk: oraclejdk8

services:
  - docker

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
  - secure: iGxjb/mQeJ0a/m2CwbCpPrGhFmUI35NiR1AsdJWCAuDmLhh+51UMpN6WTZIhFfy6bJX2CUCY8JPkUHqn1d/OKEP7wvuIhX644TtSs8l+YqdePUPHoOlrPXDAj1zlBWx5+k4aki++cuQNItRcRw5HDE6KromynDfm+6PWVudlp9wjEi6iDWUKmL5VJkAc6eyxZ1qBWFQo9ElF7oOimkgoy3IEIEltv4AkXbhZ47hZ45XQg9O9zdVCbCV06k8sNGiBiG0XcYyA/ON9wzmY7uApuAz029+vmC21VSILnwrUybLSFx8wo0rNXQPeJecxdmQ0+0SRIKVwcVKr3RYOBIzDnN8fyTLQ9Ba7Pcy/QD+ajTHEg0rFvaB9P+81eIgE2MFj9d/d96GhFMZjiNG2rAQyElXpVu0e9GXMg54c4verwAuVqBjaKyjMGZBQpxfisAj23Tu4pdG/Nd+1O8U24/KhfCu41N9RizhXdr8xHUEXhcJZzvoPrt9pA7u4xoH3lU2CGWPX8DaNBE/lDCfN/RYYCSETB8lj5dj/F0VztWCXkqgb7NH6n1eYSHIXBK+Df31nqG8pMP/gfen11KKMtzS5VQt0tT2W6KPD/97MSrzp8oVRcoGoHWqiNqH3XHyitCK2mZ/CUiicGLSG7F+VueJG6HfCy9YfUr3epSnH3CqxDMY=
  - secure: hQQPy2u2M+Rr5I8sS10SePhmRBbbUDNnH8DkCjnoHM+6r+mB2GzXo4PgNcko2ECgKj5zpSdnpougrVZPZQUg2s4BChc0U5whgSttzDIh3D7+Q7fVd32cqI5VHzmt8bwGgw1mmiFUwXmbtmPET0b72Vu8cl4sO1Bfxw1GOJ1a6dIMbX/fnKFAuo8BGvNDJUg9uX1B4Qseg8A6nyaz3EewFQbsT3WrNYf7tK/RGG8sR5LZUBkxtE3huUhdhewUABnfzK1tfqeH8p7x4FhqIw6/rY5Tumd2B0+hfMRfgKJG6sKFrTWpGxh0dMVHhh6axgL1NvSgnmpOgUXfErcFQAOgy9KdUO6Az/bgvI8ZZakdVEpt8vKz/1OgcgAyKCfME4FB2nft7moeZCDpSGv5jmJM7KFUi3WMOleQq6F4XF+g9IWE0au3Ll1gNGsou69BZNr4Q5oDm68sJ4ZnvZDF9wftAP7CzMOfLnxhFMGNLC5zD1PHrhMg6zp/GwNZrp7ufZ2j8jwPKwwgGpIslfed+xJwdqHq9Vh2IMCAcPw74VHvVebpXLnHSjCqct7sYiaYJY/gP6M8JqBmMfCPfKXy19lo4vM3icGRclwGSWwX/tpyW49KsxfR5OH0lwYwILhS7DJPG3Q9jXA4dKIXozvwNhZsUHoUFanIVh93ebNqj1miHqY=
  - secure: t0FOYNtGMAjYuBhWnZQI2baqTGcBJBHtujRkfq/KeffDmKCFjH/MdxAx1+uVGLR4Ct4IFjFse4kEcVhOw2aHu3fklGg4uvjVIFQxPGs50J4U6E9LnWl/T6SqiVhfrsYR38b9UpUYY12T8+ApesIQpNN692GCJfLLmx9qeZBt7lw7ZPAEyXTuAkpPhKVWKPLHR3A6luv4tpSQ2meR7SqZGe1Qi4tl446g3Eb7J4KUpzNfUkygiqw8JVIVaBnbLlXaQuYRwjGJpilOSxm+layfV1xCTEzwyI2czX4QXMwroaozlXCHVqyIjFP66rCKFDki3bnOv7+ciULpvvZj5l5ud6IusMa8HRt5+IdsOeCRCnS28HsEMzknvqc2GYCmnOyKKFyjkR4hTvNqS3YegLSi5Brgb3G33dOWeChz6daSAKzK/qmkf0HboISe9kc2LpzecrNg4BDszUtMtnMlFAYJ6o5wPcc/JJvCHrShGqqPP4yvF3fGjyBmsVLiZ5C3gUyCNcALKh74XkTaqna7Xxw96lWtghUXS6HGKOUSU3/y1xcU0B1t2+JyG6Nc9dgcLdRuILR/UbmRoivA0/ILYYLS6ubV9+DHZMDwOXNJm1pmWCXwQFtJKbLXJ2j2rGW+ENQ7L1+LptLrLmogz2ylsmgwj1nqwD4p1IhcAeR3lLAkGYc=

addons:
  sonarcloud:
    organization: org-sybren
    token:
      secure: $SONAR_TOKEN

install:
  - mvn clean install

script:
  - sonar-scanner

after_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push shboland/api:1.0.0
