version: '3'
services:
  api-service:
    image: shboland/api:1.0.0
    restart: always
    ports:
      - 8888:8888
    environment:
      - SPRING_PROFILES_ACTIVE=production
    links:
      - postgres-container:postgres
  
  postgres-container:
    image: postgres:9.6.3
    ports:
      - 5482:5432
    environment:
      POSTGRES_USER: pgroot
      POSTGRES_PASSWORD: pgpass
